for_window [app_id="google-chrome"] border none
for_window [app_id="org.gnome.Ptyxis"] border none
for_window [class="jetbrains-rubymine"] border none
for_window [class="jetbrains-datagrip"] border none
for_window [class="jetbrains-pycharm"] border none
for_window [class="jetbrains-idea"] border none
for_window [class="Slack"] border none
for_window [app_id="jetbrains-rubymine"] border none
for_window [app_id="jetbrains-datagrip"] border none
for_window [app_id="jetbrains-pycharm"] border none
for_window [app_id="jetbrains-idea"] border none
for_window [app_id="Slack"] border none
for_window [app_id="code"] border none
for_window [class="discord"] border none
for_window [app_id="chrome-app.slack.com__client_-Default"] mark --add 🌐 Chrome app
