#!/bin/bash
SCRIPT_DIR=$(dirname "$0")
VAR_FILE="${SCRIPT_DIR}/red_var"

# Source the red_var script to get the variable
source "${VAR_FILE}"

if pgrep -x "wlsunset" > /dev/null
then
    pkill wlsunset > /dev/null 2>&1
else
    wlsunset -t $VAR
fi
