#!/bin/bash

SCRIPT_DIR=$(dirname "$0")
VAR_FILE="${SCRIPT_DIR}/red_var"

# Source the red_var script to get the variable
source "${VAR_FILE}"

# Check if the variable is set. If not, set it to 0
if [ -z "$VAR" ]
then
    VAR=7000
fi

# Increase the variable but cap at 7000
if ((VAR < 7000))
then
    VAR=$((VAR + 200))
else
    exit 0
fi

# Update the variable in red_var
echo "VAR=$VAR" > "${VAR_FILE}"

# Print the new value of VAR
echo "New value of VAR: $VAR"

# Check if wlsunset is running
if pgrep -x "wlsunset" > /dev/null
then
    # If wlsunset is running, kill it
    pkill -9 "wlsunset"
fi

# Run wlsunset with the new value
wlsunset -t $VAR
